create table todo (
    id bigint generated by default as identity,
    created_at timestamp(6),
    deleted boolean not null,
    task_description varchar(255) not null,
    task_name varchar(255) not null,
    task_status enum ('COMPLETED','PENDING') not null,
    updated_at timestamp(6),
    primary key (id)
);

insert
into
    todo
(created_at, deleted, task_description, task_name, task_status, updated_at, id)
values
    (?, ?, ?, ?, ?, ?, default);

select
    t1_0.id,
    t1_0.created_at,
    t1_0.deleted,
    t1_0.task_description,
    t1_0.task_name,
    t1_0.task_status,
    t1_0.updated_at
from
    todo t1_0
where
    t1_0.deleted=false;


update
    todo
set
    deleted=?,
    task_description=?,
    task_name=?,
    task_status=?,
    updated_at=?
where
    id=?;



update
    todo
set
    deleted=?,
    task_description=?,
    task_name=?,
    task_status=?,
    updated_at=?
where
    id=?;
